In [1]:
import pandas as pd

In [24]:
df=pd.read_csv("C:/Users/DataScienceClasses/Data/genome_scores.csv")

In [15]:
print(df.head(6))

   movieId  tagId  relevance
0        1      1    0.02500
1        1      2    0.02500
2        1      3    0.05775
3        1      4    0.09675
4        1      5    0.14675
5        1      6    0.21700

In [16]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11709768 entries, 0 to 11709767
Data columns (total 3 columns):
 #   Column     Dtype
---  ------     -----
 0   movieId    int64
 1   tagId      int64
 2   relevance  float64
dtypes: float64(1), int64(2)
memory usage: 268.0 MB
None
            movieId         tagId     relevance
count  1.170977e+07  1.170977e+07  1.170977e+07
mean   2.584297e+04  5.645000e+02  1.164833e-01
std    3.467615e+04  3.256254e+02  1.542463e-01
min    1.000000e+00  1.000000e+00  2.500000e-04
25%    2.926000e+03  2.827500e+02  2.425000e-02
50%    6.017000e+03  5.645000e+02  5.650000e-02
75%    4.606200e+04  8.462500e+02  1.415000e-01
max    1.311700e+05  1.128000e+03  1.000000e+00

In [17]:
print(df.isnull().sum())

movieId      0
tagId        0
relevance    0
dtype: int64

In [18]:
df['revenue'] = df['relevance'] * 100
result = df.groupby('movieId')['revenue'].sum().reset_index()

print(result)

       movieId    revenue
0            1  18073.100
1            2  13478.025
2            3  10423.100
3            4   9636.150
4            5  11150.625
...        ...        ...
10376   130578   6940.650
10377   130840  13669.300
10378   131013  10956.900
10379   131168  15419.225
10380   131170  18373.325

[10381 rows x 2 columns]

In [19]:
df.head()

   movieId  tagId  relevance  revenue
0        1      1    0.02500    2.500
1        1      2    0.02500    2.500
2        1      3    0.05775    5.775
3        1      4    0.09675    9.675
4        1      5    0.14675   14.675

In [20]:
result.to_csv("movie_revenue.csv", index=False)

In [25]:
print(df.info())
print(df.isnull().sum())
print(df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11709769 entries, 0 to 11709768
Data columns (total 3 columns):
 #   Column     Dtype
---  ------     -----
 0   movieId    int64
 1   tagId      int64
 2   relevance  float64
dtypes: float64(1), int64(2)
memory usage: 268.0 MB
None
movieId      0
tagId        0
relevance    0
dtype: int64
1

In [27]:
df['relevance'] = df['relevance'].fillna(0)

In [29]:
df = df.dropna(subset=['relevance'])# Drop rows where 'relevance' is NaN

In [31]:
df['relevance'] = df['relevance'].round(4)

In [32]:
df.head()

   movieId  tagId  relevance
0        1      1     0.0250
1        1      2     0.0250
2        1      3     0.0578
3        1      4     0.0968
4        1      5     0.1468

In [34]:
df.to_csv("cleaned_genome_scores.csv", index=False)